{% set name = "lbprodrun" %}
{% set version = "1.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbProdRun-{{ version }}.tar.gz
  sha256: 41666d84ad4b5a57250f9efde58275dfa22c6d56972923313501a6a265fedff4

build:
  number: 0
  noarch: python
  entry_points:
    - lb-prod-run = LbProdRun.__main__:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools_scm
  run:
    - click ~=8.0
    - lbenv
    - packaging
    - pydantic ~=1.9.1
    - python >=3.9
    - pyyaml ~=6.0
    - typer ~=0.4.1

test:
  imports:
    - LbProdRun
  commands:
    - pip check
    - lb-prod-run --help
  requires:
    - pip

about:
  home: https://pypi.org/project/LbProdRun/
  summary: CLI for running LHCb applications from LHCbDIRAC
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
